### Import the libraries

In [57]:
import spacy
from spacy import tokenizer
import unicodedata
from bs4 import BeautifulSoup
import nltk
import string
import re
from nltk.stem import WordNetLemmatizer
from nltk.tokenize.toktok import ToktokTokenizer
import CONTRACTION_MAP
import pandas as pd

### Load the covid19 tweet data

In [58]:
rawData =pd.read_excel("COVID_19_vaccine_100.xlsx")
rawData.columns=['tweets']
rawData.head(5)

                                              tweets
0  @johensley @DarcyShepherd13 @JeffreyGuterman @...
1  May i remind you that the vaccine isnt just fo...
2  @MJAckermanMDPhD\nHi, Dr. Ackerman. I will lik...
3  Shandro, Hinshaw to give COVID-19 vaccine upda...
4  You ever Noticed This? They just announced Yes...

## Text Processing

#### Removing html tags

<span style="color:white">Often, unstructured text contains a lot of noise, especially if you use techniques like web or screen scraping. HTML tags are typically one of these components which don’t add much value towards understanding and analyzing text.</span>

In [59]:
def strip_html_tags(text):
    soup = BeautifulSoup(text, "html.parser")
    stripped_text = soup.get_text()
    return stripped_text
strip_html_tags('<html><h2>May i remind you that the vaccine isnt just for those who caught covid-19, its also to prevent it................ https://t.co/htFc4jP4CO</h2></html>')

'May i remind you that the vaccine isnt just for those who caught covid-19, its also to prevent it................ https://t.co/htFc4jP4CO'

#### Removing accented characters
<span style="color:white">Usually in any text corpus, you might be dealing with accented characters/letters, especially if you only want to analyze the English language. Hence, we need to make sure that these characters are converted and standardized into ASCII characters. A simple example — converting é to e.</span>

In [60]:
def remove_accented_chars(text):
    text = unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('utf-8', 'ignore')
    return text

remove_accented_chars('Sómě Áccěntěd těxt')
remove_accented_chars("May i remind you that the vaccine isnt just for those who caught covid-19, its also to prevent it................ https://t.co/htFc4jP4CO")

'May i remind you that the vaccine isnt just for those who caught covid-19, its also to prevent it................ https://t.co/htFc4jP4CO'

#### Expanding Contractions
<span style="color:white">Contractions are shortened version of words or syllables. They often exist in either written or spoken forms in the English language. These shortened versions or contractions of words are created by removing specific letters and sounds. In case of English contractions, they are often created by removing one of the vowels from the word. Examples would be, do not to don’t and I would to I’d. Converting each contraction to its expanded, original form helps with text standardization.</span>

In [61]:
def expand_contractions(text, contraction_mapping=CONTRACTION_MAP.CONTRACTION_MAP):
    modified_text=[]
    for words in text.split(' '):
        val = CONTRACTION_MAP.CONTRACTION_MAP.get(words)
        if val is not None:
            modified_text.append(val)
        else:
            modified_text.append(words)
    modified_text=' '.join(modified_text)
    return modified_text

expand_contractions("Y'all are enjoying this class we'd think. It is so cool isnt it?")

"Y'all are enjoying this class we would think. It is so cool is not it?"

#### Removing Special Characters
<span style="color:white">Special characters and symbols are usually non-alphanumeric characters or even occasionally numeric characters (depending on the problem), which add to the extra noise in unstructured text. Usually, simple regular expressions (regexes) can be used to remove them.</span>

In [62]:
def remove_special_characters(text, remove_digits=True):
    text = ''.join([word.lower() for word in text if word not in string.punctuation])
    text = ''.join([re.sub(r'\d+','',word) for word in text if remove_digits])
    return text

remove_special_characters("Well this was fun! What do you think? 123#@!\\//4", remove_digits=True)
#remove_special_characters("May i remind you that the vaccine isnt just for those who @caught covid-19, its also to prevent it................ https://t.co/htFc4jP4CO")

'well this was fun what do you think '

#### Removing Stopwords
<span style="color:white">Words which have little or no significance, especially when constructing meaningful features from text, are known as stopwords or stop words. These are usually words that end up having the maximum frequency if you do a simple term or word frequency in a corpus. Typically, these can be articles, conjunctions, prepositions and so on. Some examples of stopwords are a, an, the, and the like.</span>

In [63]:

stopword_list = nltk.corpus.stopwords.words('english')
tokenizer = ToktokTokenizer()
def remove_stopwords(text, is_lower_case=False):
    tokens = tokenizer.tokenize(text)
    tokens = [token.strip() for token in tokens]
    if is_lower_case:
        filtered_tokens = [token for token in tokens if token not in stopword_list]
    else:
        filtered_tokens = [token for token in tokens if token.lower() not in stopword_list]
    filtered_text = ' '.join(filtered_tokens)
    return filtered_text

remove_stopwords("Let us see if we can or can not remove against the stopwords from a sentence.")
remove_stopwords("May i remind you that the vaccine isnt just for those who caught covid-19, its also to prevent it................ https://t.co/htFc4jP4CO")

'May remind vaccine isnt caught covid-19 , also prevent ................ https://t.co/htFc4jP4CO'

#### Remomving URLS
<span style="color:white">Words which contains urls are mostly not required for the data analysis</span>

In [64]:
def url_removal(text):
    modified_text = ' '.join([words for words in text.split(' ') if words[0:4]!="http"])
    return modified_text

url_removal("May i remind you that the vaccine isnt just for those who caught covid-19, its also to prevent it................ https://t.co/htFc4jP4CO" )

'May i remind you that the vaccine isnt just for those who caught covid-19, its also to prevent it................'

### Lemmatization

In [65]:
wl =WordNetLemmatizer()
def lemmatize_text(text):
    text = ' '.join([wl.lemmatize(i) for i in text.split(' ')])
    return text

### Stemming

In [66]:
ps = nltk.PorterStemmer()
def stem_text(text):
    text = ' '.join([ps.stem(i) for i in text.split(' ')])
    return text

In [87]:
def normalize_corpus(doc, html_stripping=True, contraction_expansion=True,
                     accented_char_removal=True, text_lower_case=True, special_char_removal=True,
                     stopword_removal=True,remove_url=True, lemmatize=True,stem=True,remove_digits=True):

    normalized_corpus = []
    if html_stripping:
        doc= strip_html_tags(doc)
    # remove accented characters
    if accented_char_removal:
        doc = remove_accented_chars(doc)
    # expand contractions
    if contraction_expansion:
        doc = expand_contractions(doc)
    # lowercase the text
    if text_lower_case:
        doc = doc.lower()
    # remove extra newlines
    doc = re.sub(r'[\r|\n|\r\n]+', ' ',doc)
    # remove special characters and\or digits
    if special_char_removal:
        doc=remove_special_characters(doc,remove_digits=True)
     # remove extra whitespace
    doc = re.sub(' +', ' ', doc)
    # remove stopwords
    if stopword_removal:
        doc = remove_stopwords(doc, is_lower_case=text_lower_case)
    if remove_url:
        doc=url_removal(doc)
    #lemmatize text
    if lemmatize:
        doc = lemmatize_text(doc)
    #stemming text
    # if stem:
    #     doc = stem_text(doc)
    normalized_corpus.append(doc)
    return ' '.join(normalized_corpus)

rawData['tweets_cleaned']= rawData['tweets'].apply(lambda x:normalize_corpus(x))
rawData

C:\Users\ragha\AppData\Local\Temp\ipykernel_16480\172976477.py:2: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  soup = BeautifulSoup(text, "html.parser")

,tweets,tweets_cleaned
0,@johensley @DarcyShepherd13 @JeffreyGuterman @...,johensley darcyshepherd jeffreyguterman realdo...
1,May i remind you that the vaccine isnt just fo...,may remind vaccine caught covid also prevent
2,"@MJAckermanMDPhD\nHi, Dr. Ackerman. I will lik...",mjackermanmdphd hi dr ackerman like know going...
3,"Shandro, Hinshaw to give COVID-19 vaccine upda...",shandro hinshaw give covid vaccine update noon
4,You ever Noticed This? They just announced Yes...,ever noticed announced yesterday december th g...
...,...,...
95,Must viewing: Principles of vaccines programs ...,must viewing principle vaccine program control...
96,COVID-19 vaccine's protection against virus ou...,covid vaccine protection virus outweighs poten...
97,I've spent some time today looking into whethe...,spent time today looking whether covid vaccine...
98,COVID-19 Vaccine Likely Beneficial For Breastf...,covid vaccine likely beneficial breastfed baby...
99,Alright you guys who wants to make a trip pact...,alright guy want make trip pact cuz iatmm summ...

In [88]:
import spacy
nltk.download('averaged_perceptron_tagger')
# Download NLTK Punkt sentence tokenizer
nltk.download('punkt')
nlp = spacy.load("en_core_web_sm")
pos_tagged_data=[]
for sentence in rawData['tweets_cleaned']:
    sentence_nlp = nlp(sentence)
    spacy_pos_tagged=[]
    spacy_pos_tagged_sentence = [(word.__str__().strip(' '), word.tag_, word.pos_,sentence) for word in [i for i in sentence_nlp]]
    pos_tagged_data=pos_tagged_data+spacy_pos_tagged_sentence


spacy_pos_tagged_data = pd.DataFrame(pos_tagged_data,columns=['word','pos_tag','tag_type','sentence'])
spacy_pos_tagged_data.to_csv('spacy_pos_tagged_data.csv')
spacy_pos_tagged_data.shape

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\ragha\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ragha\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

(1624, 4)

## Question 1:

### 1A Frequency of the word covid appears in the dataset:

In [89]:
print("Frequency of the word 'covid' is: {}".format(spacy_pos_tagged_data[spacy_pos_tagged_data['word'].str.contains('covid')]['word'].count()))

Frequency of the word 'covid' is: 118

### 1B Word count of 'covid' across each pos_tag type

In [90]:
spacy_pos_tagged_data['word']=spacy_pos_tagged_data['word'].str.strip(' ')
covid_word_pos_tags = spacy_pos_tagged_data[spacy_pos_tagged_data['word'].str.contains('covid')].groupby(
    ['word','pos_tag']).size().reset_index(name='counts')
covid_word_pos_tags.to_csv('covid_word_pos_tags.csv')
covid_word_pos_tags.head(10)

             word pos_tag  counts
0           covid      JJ      64
1           covid      NN       5
2           covid     NNP      40
3           covid      VB       2
4  covidindiaseva     NNP       1
5       covidinsa      NN       1
6       covidlong     NNP       1
7  covidnewsbymib     NNP       1
8   covidvaccines     NNP       1
9   covidvaccines     NNS       1

In [91]:
covid_word_sntns_pos_tags = spacy_pos_tagged_data[spacy_pos_tagged_data['word'].str.contains('covid')].groupby(
    ['word','sentence','pos_tag']).size().reset_index(name='counts')
covid_word_sntns_pos_tags.to_csv('covid_word_sntns_pos_tags.csv')
covid_word_sntns_pos_tags.head(10)

    word                                           sentence pos_tag  counts
0  covid  alright guy want make trip pact cuz iatmm summ...     NNP       1
1  covid  amoderna expects covid vaccine protect uk coro...      JJ       1
2  covid  ano covid related death covid case requiring m...      NN       1
3  covid  ano covid related death covid case requiring m...     NNP       1
4  covid  asked answered check updated north carolina co...     NNP       1
5  covid  az scheint gut zu wirken afirst dose bntb vacc...      JJ       1
6  covid  b poll plan receiving type covid vaccine covid...      JJ       1
7  covid  baby vaccination new study suggests pfizers co...      JJ       1
8  covid  bell palsy conventional medicine say cause unk...      JJ       1
9  covid  bobwachter peter mark explained changing dose ...      NN       1

### Question 2:

## 2 Cardinal entity(CD) Count

In [92]:
pos_cardinal_count = spacy_pos_tagged_data[spacy_pos_tagged_data['pos_tag']=='CD'].groupby(["word","pos_tag"]).size().reset_index(name='counts').sort_values('counts',ascending=False)
pos_cardinal_count.to_csv('cardinal_counts.csv')
pos_cardinal_count.head(10)

      word pos_tag  counts
2      one      CD       5
4      two      CD       4
0  hundred      CD       1
1  million      CD       1
3      six      CD       1

In [93]:
spacy_pos_tagged_data[spacy_pos_tagged_data['pos_tag']=='CD']

,word,pos_tag,tag_type,sentence
577,million,CD,NUM,vernersviews anyone providing number people ma...
636,one,CD,NUM,youatmre looking thorough easytounderstand exp...
686,hundred,CD,NUM,coronavaccine govt want people trust vaccine e...
847,one,CD,NUM,davekeating mentioned earlier tweet learn covi...
1082,six,CD,NUM,december united state seen six case anaphylaxi...
1104,two,CD,NUM,december united state seen six case anaphylaxi...
1255,one,CD,NUM,novavax say covid vaccine effective far le one...
1296,two,CD,NUM,dad demand answer health worker daughter died ...
1332,two,CD,NUM,heathdonsmcgreg mfwitches itatms good skeptica...
1395,one,CD,NUM,rrrbyn covid vaccine use one two human fetal c...
1396,two,CD,NUM,rrrbyn covid vaccine use one two human fetal c...
1528,one,CD,NUM,californiaatms state epidemiologist urged covi...

### Question 3

### NER

In [94]:
def gen_ents(snts):
    if snts.ents:
        for i in snts.ents:
            print(i.text+' - '+i.label_)

In [111]:
ner_tags=[]
for i in rawData['tweets_cleaned']:
    doc = nlp(i)
    print(doc)
    if doc.ents:
        ner_tags= ner_tags+[(ent.text,ent.label_) for ent in doc.ents]
    else:
        print(i)

ner_tags_data =pd.DataFrame(ner_tags,columns=['text','label'])

johensley darcyshepherd jeffreyguterman realdonaldtrump different vaccine different ingredient take covid second efficacy fine also thevaccine made recombinant dna made mrna really hate people spread misinformation luciferase enzyme vaccine
may remind vaccine caught covid also prevent
may remind vaccine caught covid also prevent
mjackermanmdphd hi dr ackerman like know going discus safe covid vaccine lqts patient
shandro hinshaw give covid vaccine update noon
ever noticed announced yesterday december th great vaccine protect covid effective took le year develop yet still cure cancer year
covidlong longcovid anaphylaxis troublesome year problem ade cv vaccine covid vaccine designed elicit neutralizing antibody may sensitize vaccine recipient severe disease vaccinated
b poll plan receiving type covid vaccine covidvaccines
b poll plan receiving type covid vaccine covidvaccines
covid vaccine safety efficacy important brand adoctors
hour post nd covid vaccine body ache headache lowgrade temp shiver would take vaccine heartbeat really glad vaccinated covid moderna
update government tuesday stated covid vaccine also work new variant virus proof current vaccine fail guard sarscov mutant claimed uk south africa
ano covid related death covid case requiring medical intervention occurring day postvaccination among participant age year older medical comorbidities vaccine groupa
asked answered check updated north carolina covid vaccine faq
bobwachter peter mark explained changing dose vaccine regimen dose immune response could dwindle faster know happen know already people get mild covid tend lose immune response pretty quickly min mark
nvax share premarket co say covid vaccine effective uk trial nvax breakout alert lookout take
nvax share premarket co say covid vaccine effective uk trial nvax breakout alert lookout take
usfda approved first covid vaccine emergency use vaccine safe effective help u defeat virus extremely confident vaccine participating pfizer vaccine trial
get covid vaccine since beijing begin inoculation serious side effect observed among vaccine receiver spokesperson municipal health commission told press briefing covid
highrisk pregnant breastfeeding woman get covid vaccine oma cp toronto breaking news published canada news medium news
nanovaccine institute develops nextgeneration covid vaccine iowa state university
covid vaccine alone end pandemic take question expert wftv tonight kraywftva vecholswftva meganwftv
novavax publishes positive efficacy data covid vaccine read
covid single vaccine dose lead greater risk new coronavirus variant south african expert warn skynews
holy grail vaccine research could blood test show covid vaccine work search
holy grail vaccine research could blood test show covid vaccine work search
british medical journal editorial covid vaccine efficacy vaccine studied determine whether interrupt transmission virus
nbaatms dr leroy sims covid vaccine undefeated
censored doctor genetically modify u covid vaccine
think twice get covid vaccine
think twice get covid vaccine
take covid vaccine test subject experimental mrna vaccine tested ever
nice infographic covid vaccine compare unbiasedscipod
nice infographic covid vaccine compare unbiasedscipod
generous offer always tune profsuperjunior help query concern etc people may covid vaccine right contact access right information know find already posting v useful information ty gabrielle
new result astrazeneca covid vaccine candidate suggest safe effective news
week episode covid myth busting mara aspinall debunks several myth asked listener skepticism around new technology used vaccine testing preference susceptibility kid finally discussing
week episode covid myth busting mara aspinall debunks several myth asked listener skepticism around new technology used vaccine testing preference susceptibility kid finally discussing
marcorubio need vaccine mr rubio covid hoax like flu itll disappeared april k dead people die virus tell getting vaccine
data pertaining trial made public expert covid vaccine choice
data pertaining trial made public expert covid vaccine choice
mythbusters covidvaccines amyth vaccine needed covid recovered person afact advisable receive complete schedule vaccine despite recovery covid enhance immune response wevaccine unitefightcorona indiafightscorona
mythbusters covidvaccines amyth vaccine needed covid recovered person afact advisable receive complete schedule vaccine despite recovery covid enhance immune response wevaccine unitefightcorona indiafightscorona
covid vaccinesatm trial done long period enough pas efficacy safety protocol normally applied vaccine community leader need provide accurate information constituency scientist please help
covid vaccinesatm trial done long period enough pas efficacy safety protocol normally applied vaccine community leader need provide accurate information constituency scientist please help
see microchip cannot put using covid vaccine plus need bigger largescale tracking extremely close range someone track cell phone use spread false information stupidly easier
see microchip cannot put using covid vaccine plus need bigger largescale tracking extremely close range someone track cell phone use spread false information stupidly easier
vernersviews anyone providing number people may suffered serious side effect perhaps death must take following number account many million st dos vaccine proving safe vastly safer covid course
vernersviews anyone providing number people may suffered serious side effect perhaps death must take following number account many million st dos vaccine proving safe vastly safer covid course
cp implore everyone reading look well known safe alternative vaccine called ivermectin several case study around world shown recovery rate ill covid ivermectin also work preventative
uhuh ontario government say incorrectly reporting covid vaccine data
youatmre looking thorough easytounderstand explanation covid vaccine work hint doesnatmt work way flu vaccine one great contains perfect amount swearing scientific technological achievement
youatmre looking thorough easytounderstand explanation covid vaccine work hint doesnatmt work way flu vaccine one great contains perfect amount swearing scientific technological achievement
nanotechnology new hazard mrna covid vaccine lipid nanoparticles atmnanoatm particle many known harmful effect
tonight doctor express concern pregnant woman vaccinated covid debunking myth vaccine infertility
moderna reveals final result covid vaccine
moderna reveals final result covid vaccine
coronavaccine govt want people trust vaccine efficacy shekhargupta jhasanjay hundred died covid infection included gujarat tally report
question covid vaccine hear medical expert community leader public health professional ohioatms covid vaccine town hall caresourceemployee
question covid vaccine hear medical expert community leader public health professional ohioatms covid vaccine town hall caresourceemployee
hello amalia valid point sudden switch prioritised inoculated vaccine data stop asymptomatic spread virus extent prevent people developing severe covid hq biontech mainz germany diana
stop wearing mask getting covid vaccine answer
stop wearing mask getting covid vaccine answer
baby vaccination new study suggests pfizers covid vaccine work mom
baby vaccination new study suggests pfizers covid vaccine work mom
risk v benefit know covid vaccine side effect
risk v benefit know covid vaccine side effect
nqosy positive vaccine expected virus causing covid first attenuated weakened point cause disease activate antibody introduced antigen sometimes immune disease developed greatpmkgmailcom
dr kevin covid vaccine another strain coronavirus influenza
cjsienna lynnbrittney trusttruth lindsaypuppyd covid single vaccine dose lead greater risk new coronavirus variant south african expert warn variant thought responsible infection south africa already found uk
death associated new covid vaccine misinformation time honesty pharmaceutical medical establishmenthttpstcobjyveha
death associated new covid vaccine misinformation time honesty pharmaceutical medical establishmenthttpstcobjyveha
davekeating mentioned earlier tweet learn covid vaccination adapt evolve france st country give dos vaccine person already covid one injection booster
az scheint gut zu wirken afirst dose bntb vaccine associated vaccine effect covid related hospitalisation day postvaccination vaccine effect time interval chadox vaccine
y pollys amarach research q concern getting covid vaccine yes female male th january th november
get vaccine dangerous unless severe allergy dont dingus wear mask get vaccinated asap high percentage frontline worker refusing take covid vaccine many citing political reason via googlenews
get vaccine dangerous unless severe allergy dont dingus wear mask get vaccinated asap high percentage frontline worker refusing take covid vaccine many citing political reason via googlenews
pfizer test booster shot develop adapted vaccine address variant concern covid coronavirus
pfizer test booster shot develop adapted vaccine address variant concern covid coronavirus
join u informative session dr kubi covid vaccine safe effective detail follow kubimedical kubiweightloss weightlossjourney
johnwcurtis wonder mutation permitting vaccine facilitates herdimmunity time enough people immunised andor caught covid survived herdimmunity policy posited last year without vaccineextant societal immunity dangerous nonsense
novavax covid vaccine demonstrates efficacy ina uk phase trial novavax inc ir site acityofresearcha led way absolutely delighted news adocjohnwrighta
involved government agency communication join u communicator coffee chat fri dec theme covid vaccine insight challenge best practice dm addl info agencywork govit communitybuilding eventsprofs govmil email address reqd
citynews unacceptable understand need certain vaccination rushed thoroughly tested version forced anyone threat repercussion know side effect vaccine could bad worse covid
citynews unacceptable understand need certain vaccination rushed thoroughly tested version forced anyone threat repercussion know side effect vaccine could bad worse covid
covid vaccine fake donatmt take
vaccine common cold researched decade vaccine vaccine flu reserched decade never sure flu vacc apply vaccine covid researched tested ready rolloutwithin month
vaccine common cold researched decade vaccine vaccine flu reserched decade never sure flu vacc apply vaccine covid researched tested ready rolloutwithin month
different efficacy data chinese covid vaccine real validmedia yahoo news
december united state seen six case anaphylaxis among people received covid vaccine according recent presentation thomas clark u center disease control prevention cdc united kingdom recorded two
top epidemiologist urge single dos covid vaccine foxnews
top epidemiologist urge single dos covid vaccine foxnews
brazilian health regulator anvisa said chinese health authority transparent experimental covid vaccine
covid vaccine communication handbook aim fight misinformation demonstrate vaccine safe effective put together renowned team scientific expert range discipline here thread may interest cddftnhs colleague
johnson johnsonatms oneshot covid vaccine show promise earlystage trial
mohfwindia pmoindia drharshvardhan ashwinikchoubey pibindia mygovindia covidnewsbymib covidindiaseva everyone take covid vaccine protect covid end coronavirus pandemic
medstar health launch study understand covid spread symptom vaccine adoption
medstar health launch study understand covid spread symptom vaccine adoption
covid vaccination whatatms evidence extending dosing interval bmj grateful interpretation reading oxford vaccine better efficacy dose wks pfizer dose must le week correct
yjiden michaelbarden covid total scam fool believe whatever govt msm tell obviously fake plandemic mask work there thing asymptomatic transmission virus deluded myth vaccine harm u
woman experience side effect covid vaccine covid vaccine side effect common nd dose
woman experience side effect covid vaccine covid vaccine side effect common nd dose
novavax say covid vaccine effective far le one variant via statnews pharma covid coronavirus vaccine nvax
wisconsin pharmacist accused trying destroy covid vaccine admitted conspiracy theorist told investigator believed covid vaccine safe people could harm change dnaa
northern light covid vaccine
dad demand answer health worker daughter died two day covid vaccine
bell palsy conventional medicine say cause unknown go away time there growing evidence caused vaccine especially flu covid pharmaceutical industry seem interested investigating wonder bellspalsy
heathdonsmcgreg mfwitches itatms good skeptical point claim two vaccine hold fda approves good enough chance possible side effect showing road v chance covid right balancing ymmv
uwu weseawchews uwged govewnments deway administewing da second dose pfizew inc covid vaccine said efficacy aftew da fiwst dose
wearing mask keeping social distance washing hand best covid vaccine covidinsa
wearing mask keeping social distance washing hand best covid vaccine covidinsa
say vaccine use live virus cannot give someone covid
say vaccine use live virus cannot give someone covid
rrrbyn covid vaccine use one two human fetal cell line hek kidney cell line widely used research industry come fetus aborted perc proprietary cell line owned johnson johnson developed fetus aborted
new cwmh blog pregnant woman covid vaccine
question remain around strategy curb continued spread covid join u webinar tomorrow noon expert answer question vaccine treatment prevention expect going forward register
amoderna expects covid vaccine protect uk coronavirus variant reutersa
question working get covid vaccine question answered concern vaccine let u know covid story found
question working get covid vaccine question answered concern vaccine let u know covid story found
first shot florida teen start covid vaccine trial journey
dr anthony fauci top infectious disease specialist united state say pfizerbiontech moderna vaccine effective could crush covid pandemic spoke white coat black art host dr brian goldman
covid vaccine bringing infection show israela study
californiaatms state epidemiologist urged covid vaccine provider pause distribution one moderna vaccine lot investigate ahigher usuala number allergic reaction
interessante video banned youtube dr simone gold share truth covid vaccine
interessante video banned youtube dr simone gold share truth covid vaccine
must viewing principle vaccine program control covid via youtube
must viewing principle vaccine program control covid via youtube
covid vaccine protection virus outweighs potential allergy risk expert say cbc
spent time today looking whether covid vaccine dos going waste people cannot attend appointment etc healthcare staff spoken say problem offer dos others short notice
covid vaccine likely beneficial breastfed baby question remain via kpbsnews
alright guy want make trip pact cuz iatmm summer covid vaccine safe people arenatmt suffering bell palsy side effect
alright guy want make trip pact cuz iatmm summer covid vaccine safe people arenatmt suffering bell palsy side effect

In [112]:
doc = nlp("alright guy want make trip pact cuz iatmm summer covid vaccine safe people arenatmt suffering bell palsy side effect")

In [113]:
for i in doc.ents:
    print(i.text,i.label_)